### ISSUE TITLE
onScreenChange is not invoked (next/prev buttons and pagination toggles)

### ISSUE THREAD

**Issue by brogan89** [brogan89/ScreenSwipe#3]
`onScreenChange` is not invoked when when clicking next/prev buttons or pagination toggles.
the event should be invoked any time a screen has changed.

**Comment by brogan89** [comment]
Just tested this now and it seems to be working fine. Don't know why I made this issue now. Was I drunk? Maybe, who knows.

**Comment by mrtorrent** [comment]
I've just run into this issue, and am not currently drunk, I swear. It became apparent because I am using next/prev buttons but no toggles.

There are a couple of parts to this problem. The most directly related is that `onScreenChanged` is not invoked consistently when the screen is changed. Instead, it is invoked only in `ScreenChangeValidate()` — which is called only for a drag event — and in `PaginationToggleCallback()` — which is called only if there is a pagination group with toggles. Therefore, if you're not using pagination, pressing a button to trigger a screen change does not invoke the `onScreenChanged` event.

It seems like, if `GoToScreen()` is where screen changes ultimately happen, then it would be more consistent if `onScreenChanged` was invoked directly within that method.

The other part to this problem, or maybe a separate issue in itself, is that `PaginationToggleCallback()` gets triggered multiple times, and also causes `GoToScreen()` to run multiple times. I'm having a little trouble unpicking this, because setting a toggle to On triggers Unity's `ToggleGroup.NotifyToggleOn()` which iterates through all the toggles in the group, switching the others off, and triggering `onValueChanged` callbacks for all of them. I'm not quite sure why `PaginationToggleCallback()` is passing the `if (!isOn)` test more than once, however.

What I can tell you, is that at startup, in `Pagination_Init()`, the toggle callback is executed four times with `isOn = true`. For every screen change after that, whether activated by drag, button, or toggle, it executes three times. With a drag, it never passes the `if (isSwipe)` test, but button or toggle-based navigation cause it to invoke `onScreenChanged` all three times it runs. This also means it is recursively calling `GoToScreen`.

**Comment by brogan89** [comment]
I haven't looked at this code in a long time and don't use the package anymore so I'll just take your word for it haha
