### ISSUE TITLE
[Feature] Freely scrolling

### ISSUE THREAD

**Issue by vangogih** [brogan89/ScreenSwipe#4]
Hi, thanks for you work.

I adding small feature (in my project) "freely scrolling". The essence is simple, add a button (in Editor) that allows or not to freely scroll through screens. 

Use case: user can swipe under the last screen and see background (which may not be). If "freely scrolling" enable (true), user can drag screen how them want, else (false) them can swipe only between anchoredPosition.

Feature so small, but so efficient.

1. In ScreenSwipe.cs adding field:
```cs
[SerializeField]
[Tooltip("(true), user can drag screen how them want, else (false) them can swipe only between anchoredPosition.")]
private bool freelyScrolling;
```

2. In SetContentAnchoredPosition in third condition add:
```cs
if (swipeType == SwipeType.Vertical) position.x = content.anchoredPosition.x;
if (swipeType == SwipeType.Horizonal) position.y = content.anchoredPosition.y;

if (position != content.anchoredPosition)
{

    if (freelyScrolling) content.anchoredPosition = position;
    UpdateBounds();
}
```

I can create Pull Request or you can make changes yourself. Anyway let me know about you decision.

**Comment by brogan89** [comment]
I'm sorry I don't quite understand what you are trying to achieve. What I think you are saying is that you want an option that doesn't allow the user the drag the screens? If that is the case you can uncheck the `isInteractable` bool which will turn off dragging but still allow the user to change screens with buttons or pagination toggles. I tried your code, but it didn't seems to make a lot of sense to me. It just broke the ability to change screens at all unless it was true.

If it is clamping you want, so no stretching beyond the end screens which exposes the background, it can be achieved, but I would solve that a different way. I actually quite like that idea and I have implemented it in commit e44362d170b1428252198351eb30f7f59aac12c6.

Let me know if that helps :)

**Comment by vangogih** [comment]
Thank you for answer and good feature.

My main task is to clamp all the screens, not just the last ones. I [record](https://gph.is/g/ZrKK1yw) the git image for introduce my thinks.

Also please share your plans for developing this script. 

- I could modify it and apply Microsoft rules for naming variables. Also, I can split this script into several scripts that will perform their small function. In my opinion, this should simplify reading and work. 

- I also adapted your script under the [DoTween](http://dotween.demigiant.com/index.php) plugin, I can also add this. 

- We can also coordinate API for public methods so that the script can be conveniently used without additions.

- I also found a bug with calling the `onScreenChanged` event.

**And now I realized that I downloaded the script from the Release tab.**

**Comment by brogan89** [comment]
> I could modify it and apply Microsoft rules for naming variables. Also, I can split this script into several scripts that will perform their small function. In my opinion, this should simplify reading and work.

I am pretty relaxed on the variable names. Though I am starting to become more accustom to some naming conventions. You can change them if you want. I really don't mind. 

The separate scripts idea I don't particularly like though. If you can find a way to make it one component that will be fine, but a developer shouldn't have to drag multiple scripts onto the gameObject to get this functionality. It should be easy for developer.

> I also adapted your script under the DoTween plugin, I can also add this.

The only tweening in this does is between screens its nothing fancy so making a dependency for DoTween is not worth it. The coroutine is enough I think, there is an animation curve too incase the developer wants to chase the ease type.

If you want to fork the repo and change it to how you like go a head :) I just want to keep this package as light weight as possible.

> I also found a bug with calling the onScreenChanged event.

Oh, I would like to know what the bug is. Maybe make another issue to focus on that?

**Comment by vangogih** [comment]
Ok, thank you for you reply.

> Oh, I would like to know what the bug is. Maybe make another issue to focus on that?

Yes, sure, but first me need download and check original script, not from Release tab.
